"""
Lightweight Markdown → HTML converter for EOD email formatting.
Handles: headers, bold, italic, tables, unordered/ordered lists, horizontal rules.
"""
from __future__ import annotations
import re


def md_to_html(md: str) -> str:
    lines = md.splitlines()
    html_lines: list[str] = []
    in_ul = False
    in_ol = False
    in_table = False
    table_rows: list[str] = []

    def flush_table() -> None:
        nonlocal in_table, table_rows
        if not table_rows:
            in_table = False
            return
        html = '<table border="1" cellpadding="6" cellspacing="0" style="border-collapse:collapse;width:100%">\n'
        for i, row in enumerate(table_rows):
            cells = [c.strip() for c in row.strip("|").split("|")]
            tag = "th" if i == 0 else "td"
            html += "  <tr>" + "".join(f"<{tag}>{c}</{tag}>" for c in cells) + "</tr>\n"
        html += "</table>"
        html_lines.append(html)
        table_rows = []
        in_table = False

    def inline(text: str) -> str:
        text = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", text)
        text = re.sub(r"\*(.+?)\*",     r"<em>\1</em>",         text)
        text = re.sub(r"`(.+?)`",        r"<code>\1</code>",     text)
        return text

    for line in lines:
        stripped = line.rstrip()

        # Table
        if "|" in stripped and stripped.startswith("|"):
            if not in_table:
                in_table = True
                table_rows = []
            if re.match(r"^\|[-| :]+\|$", stripped):
                continue  # separator row
            table_rows.append(stripped)
            continue
        if in_table:
            flush_table()

        # Close open lists
        if in_ul and not stripped.startswith(("- ", "* ")):
            html_lines.append("</ul>")
            in_ul = False
        if in_ol and not re.match(r"^\d+\.", stripped):
            html_lines.append("</ol>")
            in_ol = False

        # Headers
        m = re.match(r"^(#{1,6})\s+(.*)", stripped)
        if m:
            level = len(m.group(1))
            html_lines.append(f"<h{level}>{inline(m.group(2))}</h{level}>")
            continue

        # Horizontal rule
        if re.match(r"^[-*_]{3,}$", stripped):
            html_lines.append("<hr>")
            continue

        # Unordered list
        m = re.match(r"^[-*]\s+(.*)", stripped)
        if m:
            if not in_ul:
                html_lines.append("<ul>")
                in_ul = True
            html_lines.append(f"  <li>{inline(m.group(1))}</li>")
            continue

        # Ordered list
        m = re.match(r"^\d+\.\s+(.*)", stripped)
        if m:
            if not in_ol:
                html_lines.append("<ol>")
                in_ol = True
            html_lines.append(f"  <li>{inline(m.group(1))}</li>")
            continue

        # Empty line
        if not stripped:
            html_lines.append("<br>")
            continue

        # Paragraph
        html_lines.append(f"<p>{inline(stripped)}</p>")

    if in_ul:
        html_lines.append("</ul>")
    if in_ol:
        html_lines.append("</ol>")
    if in_table:
        flush_table()

    return "\n".join(html_lines)


EOD_EMAIL_TEMPLATE = """\
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
  body {{ font-family: Arial, sans-serif; max-width: 800px; margin: 0 auto; color: #333; }}
  h1 {{ color: #1a73e8; border-bottom: 2px solid #1a73e8; padding-bottom: 8px; }}
  h2 {{ color: #185abc; margin-top: 24px; }}
  h3 {{ color: #444; }}
  table {{ width: 100%; border-collapse: collapse; margin: 16px 0; }}
  th {{ background: #1a73e8; color: #fff; padding: 8px; text-align: left; }}
  td {{ padding: 8px; border-bottom: 1px solid #ddd; }}
  tr:hover {{ background: #f9f9f9; }}
  code {{ background: #f4f4f4; padding: 2px 4px; border-radius: 3px; }}
  hr {{ border: none; border-top: 1px solid #ddd; margin: 20px 0; }}
  .footer {{ margin-top: 32px; padding-top: 16px; border-top: 1px solid #ddd;
             font-size: 12px; color: #777; }}
</style>
</head>
<body>
{body}
<div class="footer">Generated by Email Manager · {date}</div>
</body>
</html>
"""


def format_eod_html_email(markdown_summary: str, date: str) -> str:
    body = md_to_html(markdown_summary)
    return EOD_EMAIL_TEMPLATE.format(body=body, date=date)
